from .config_so_follower import SOFollowerRobotConfig

class _FollowerBus:
    def connect(self) -> None: ...
    def sync_read(self, register: str, *, normalize: bool) -> dict[str, float | int]: ...
    def disconnect(self, *, disable_torque: bool) -> None: ...

class SOFollower:
    bus: _FollowerBus
    def __init__(self, config: SOFollowerRobotConfig) -> None: ...
