#!/usr/bin/env bash
# Local sequential training runner with resource caps (systemd-run).
#
# Trains the four models one at a time on the local GPU using the derived
# single-camera 96x96 freeze, with CPU/RAM/nice caps so the desktop stays
# usable. Each model uses the local exploratory budget (PUSHT_LOCAL_BUDGET=1).
#
# Usage:
#   bash scripts/local_run_training.sh start    # launch first model (DP-CNN)
#   bash scripts/local_run_training.sh status   # show running/logs
#   bash scripts/local_run_training.sh stop     # stop current model
#
# The runner is one systemd transient unit per model, chained sequentially
# via RemainAfterExit=no + After=. Models: dp_cnn -> dp_transformer -> ibc
# -> lstm_gmm. Output goes to /data/df/.../models/local_200ep/<model>/seed-0.
set -euo pipefail

export DF=/data/df/02_InTro_Project
export PKG=/home/intro/InternLab/02_InTro_Project/03_code/so101_pusht_benchmark
export ART=$DF/04_experiments/so101_pusht_benchmark
export VENV=/data/df/venvs/paper-baselines-local
export PY=$VENV/bin/python
export DATASET=$ART/datasets/frozen_four_model_200ep_s96
export OUT_ROOT=$ART/models/local_200ep
export SEED=0

# Resource caps: 4 CPU cores, 14GB RAM, nice 15 (desktop keeps 8 cores + 16GB).
export CPU_QUOTA=400%
export MEMORY_MAX=14G
export NICE=15

MODELS=(dp_cnn dp_transformer ibc lstm_gmm)

# Start point: skip already-published models (e.g. after DP-CNN publish, use
# START_MODEL=dp_transformer to continue the sequence without re-running
# dp_cnn against its existing output dir).
START_MODEL="${START_MODEL:-dp_cnn}"
for _m in "${MODELS[@]}"; do
  if [ "$_m" = "$START_MODEL" ]; then break; fi
  MODELS=("${MODELS[@]:1}")
done

train_one() {
  local model=$1
  local out=$OUT_ROOT/$model/seed-$SEED/full
  echo "=== starting $model (seed $SEED) ==="
  PUSHT_SINGLE_CAM=1 PUSHT_LOCAL_BUDGET=1 \
    WANDB_MODE=offline MUJOCO_GL=egl \
    PYTHONPATH="$PKG/src:$ART/cache/upstream/stanford:$ART/cache/upstream/robomimic" \
    "$PY" -m so101_pusht_benchmark.cli train-model \
      --paper-view "$DATASET" \
      --output "$out" \
      --model "$model" \
      --seed "$SEED" \
      --max-updates 400000 \
      --training-mode full_production
}

case "${1:-}" in
  start)
    if [ -f "$ART/models/local_200ep/.train.pid" ] && kill -0 "$(cat "$ART/models/local_200ep/.train.pid")" 2>/dev/null; then
      echo "training already running (pid $(cat "$ART/models/local_200ep/.train.pid"))"
      exit 0
    fi
mkdir -p "$ART/models/local_200ep"
    LOG="$ART/models/local_200ep/train.log"
    # Resource caps via systemd-run --scope (verified: --scope applies MemoryMax
    # and CPUQuota on this host; --unit transient services are broken by inotify
    # ENOSPC, and Nice is not a scope property — applied via `nice -n 15` below).
    # CPU 4 cores / RAM 14G / nice 15 (binding local-run resource contract).
    nohup systemd-run --user --scope --expand-environment=yes \
      --property=MemoryMax=14G \
      --property=CPUQuota=400% \
      --property=TasksMax=512 \
      bash -c '
      set -e
      export DF=/data/df/02_InTro_Project
      export PKG=/home/intro/InternLab/02_InTro_Project/03_code/so101_pusht_benchmark
      export ART=$DF/04_experiments/so101_pusht_benchmark
      export PY=/data/df/venvs/paper-baselines-local/bin/python
      export DATASET=$ART/datasets/frozen_four_model_200ep_s96
      export OUT_ROOT=$ART/models/local_200ep
      MODELS="dp_cnn dp_transformer ibc lstm_gmm"
      START_MODEL="${START_MODEL:-dp_cnn}"
      _skip=1
      for _candidate in $MODELS; do
        if [ "$_candidate" = "$START_MODEL" ]; then _skip=0; fi
        if [ "$_skip" = "0" ]; then _RUN_MODELS="$_RUN_MODELS $_candidate"; fi
      done
      for m in $_RUN_MODELS; do
        case "$m" in
          dp_cnn|dp_transformer) BUDGET=400000 ;;
          ibc) BUDGET=100000 ;;
          lstm_gmm) BUDGET=300000 ;;
        esac
        echo "=== starting $m (seed 0) budget=$BUDGET ==="
        # Clean regenerated bytecode under the upstream checkout: verify_pusht_so100
        # (called unconditionally by PaperBaselineRunner.run -> env_factory ->
        # load_frozen_pusht every epoch end) rejects __pycache__/*.pyc as
        # "ignored executable artifacts". PYTHONDONTWRITEBYTECODE stops re-creation.
        find "$PKG/../05_references/external_repos/pushT-so100" -name '*.pyc' -delete 2>/dev/null || true
        PUSHT_SINGLE_CAM=1 PUSHT_LOCAL_BUDGET=1 \
          PUSHT_CHECKPOINT_EVERY=25000 \
          WANDB_MODE=offline MUJOCO_GL=egl PYTHONDONTWRITEBYTECODE=1 \
          PYTHONPATH="$PKG/src:$ART/cache/upstream/stanford:$ART/cache/upstream/robomimic" \
          taskset -c 0-3 nice -n 15 \
          "$PY" -m so101_pusht_benchmark.cli train-model \
            --paper-view "$DATASET" \
            --output "$OUT_ROOT/$m/seed-0/full" \
            --model "$m" --seed 0 --artifact-id "local-$m-seed0" \
            --artifact-index "$ART/artifact-index.json" \
            --paper-profiles "$PKG/configs/experiment/pusht_so100_paper_faithful_200ep_local_v1.yaml" \
            --max-updates "$BUDGET" --full-production
      done
      echo "ALL_MODELS_DONE"
    ' > "$LOG" 2>&1 &
    echo $! > "$ART/models/local_200ep/.train.pid"
    echo "started pid $! — log: $LOG (systemd-run --scope: MemoryMax=14G/CPUQuota=400%/Nice=15)"
    ;;
  status)
    PIDFILE="$ART/models/local_200ep/.train.pid"
    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
      echo "training RUNNING (pid $(cat "$PIDFILE"))"
    else
      echo "training not running"
    fi
    echo "--- tail train.log ---"
    tail -25 "$ART/models/local_200ep/train.log" 2>/dev/null || echo "(no log yet)"
    ;;
  stop)
    PIDFILE="$ART/models/local_200ep/.train.pid"
    if [ -f "$PIDFILE" ]; then
      kill "$(cat "$PIDFILE")" 2>/dev/null && echo "stopped pid $(cat "$PIDFILE")" || echo "pid already gone"
      rm -f "$PIDFILE"
    else
      echo "no pid file — nothing to stop"
    fi
    ;;
  *)
    echo "usage: $0 {start|status|stop}"
    exit 2
    ;;
esac
