class GamepadTeleopConfig:
    def __init__(self, use_gripper: bool = ...) -> None: ...

class _Gamepad:
    running: bool

class GamepadTeleop:
    gamepad: _Gamepad | None
    def __init__(self, config: GamepadTeleopConfig) -> None: ...
    @property
    def is_connected(self) -> bool: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def get_action(self) -> dict[str, float]: ...
    def get_teleop_events(self) -> dict[str, bool]: ...
