from collections.abc import Callable
from typing import overload

class MonkeyPatch:
    @overload
    def setattr(self, target: str, value: object) -> None: ...
    @overload
    def setattr(self, target: object, name: str, value: object) -> None: ...
    def setenv(self, name: str, value: str, prepend: str | None = None) -> None: ...
    def delenv(self, name: str, raising: bool = True) -> None: ...

class _Raises:
    value: BaseException

    def __enter__(self) -> object: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool: ...

class _Mark:
    def parametrize(
        self, argnames: object, argvalues: object
    ) -> Callable[[Callable[..., object]], Callable[..., object]]: ...

mark: _Mark

def raises(expected_exception: type[BaseException], *, match: str | None = None) -> _Raises: ...
def approx(expected: object, *, rel: float | None = None, abs: float | None = None) -> object: ...
