from collections.abc import Sequence
from typing import Any

import numpy as np
from numpy.typing import NDArray

class ArrowException(Exception): ...

class DataType:
    @property
    def list_size(self) -> int: ...
    @property
    def value_type(self) -> DataType: ...

class Array: ...

class Field:
    @property
    def type(self) -> DataType: ...

class Schema:
    def field(self, name: str) -> Field: ...

class ChunkedArray:
    def to_pylist(self) -> list[Any]: ...
    def to_numpy(self) -> NDArray[np.generic]: ...
    def slice(self, offset: int, length: int) -> ChunkedArray: ...

class Table:
    @property
    def column_names(self) -> list[str]: ...
    @property
    def schema(self) -> Schema: ...
    @property
    def num_rows(self) -> int: ...
    def __getitem__(self, name: str) -> ChunkedArray: ...
    def to_pylist(self) -> list[dict[str, Any]]: ...
    def set_column(self, index: int, name: str, values: Array) -> Table: ...

class _Types:
    def is_fixed_size_list(self, value: DataType) -> bool: ...
    def is_float32(self, value: DataType) -> bool: ...
    def is_int64(self, value: DataType) -> bool: ...

types: _Types

def concat_tables(tables: Sequence[Table], *, promote_options: str = ...) -> Table: ...
def array(values: object, type: DataType) -> Array: ...
def float32() -> DataType: ...
def float64() -> DataType: ...
def int64() -> DataType: ...
def list_(value_type: DataType, list_size: int) -> DataType: ...
